{% set name = "fenics-ufl" %}
{% set version = "2023.1.1.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  url: https://github.com/fenics/ufl/archive/{{ version }}.tar.gz
  sha256: 9e6e87f1447635029cec42604f62a76bba84899beb4b8822af10389d1f93a9b6

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install --no-deps -vv .

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools >=58
    - wheel
  run:
    - python >=3.7
    - numpy
test:
  requires:
    - pip
  imports:
    - ufl
  commands:
    - pip check

about:
  home: https://fenicsproject.org
  summary: Unified Form Language
  description: |
    The Unified Form Language (UFL) is a domain specific language
    for declaration of finite element discretizations of variational forms.
    More precisely, it defines a flexible interface for choosing finite element spaces
    and defining expressions for weak forms in a notation close to mathematical notation.

    UFL is part of the FEniCS Project.
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://fenics.readthedocs.io/projects/ufl/en/latest/
  dev_url: https://github.com/fenics/ufl

extra:
  recipe-maintainers:
    - minrk
